<h3>About the Master Key System</h3>

<p>
This domain delivers the Master Key System in its orginally intended form: as a
weekly mail course. After registration the first chapter of this very condensed book
will be immediatly unlocked. 
</p>
<p>
The book consists of 24 chapters. Every week a registered member will receive an
e-mail over a period of 24 weeks. Spreading the information over a period of 6 months. 
</p>

<p>
This site is completely free of charge.
</p>

<p>
Regards,
The Master Key Team
</p>
