<h3>FORWARD</h3>

<p>
Some men seem to attract success, power, wealth, attainment, with very little
conscious effort; others conquer with great difficulty; still others fail
altogether to reach their ambitions, desires and ideals. Why is this so: Why
should some men realize their ambitions easily, others with difficulty, and
still others not at all? The cause cannot be physical, else the most perfect
men, physically, would be the most successful. The difference, therefore, must
be mental - must be in the mind; hence mind must be the creative force, must
constitute the sole difference between men. It is mind, therefore, which
overcomes environment and every other obstacle in the path of men. 
</p>

<p>
When the creative power of thought is fully understood, its effect will be seen
to be marvelous. But such results cannot be secured without proper application,
diligence, and concentration. The student will find that the laws governing in
the mental and spiritual world are as fixed and infallible as in the material
world. To secure the desired results, then, it is necessary to know the law and
to comply with it. A proper compliance with the law will be found to produce the
desired result with invariable exactitude. The student who learns that power
comes from within, that he is weak only because he has depended on help from
outside, and who unhesitatingly throws himself on his own thought, instantly
rights himself, stands erect, assumes a dominant attitude, and works miracles.
</p>

<p>
It is evident, therefore, that he who fails to fully investigate and take
advantage of the wonderful progress which is being made in this last and
greatest science, will soon be as far behind as the man who would refuse to
acknowledge and accept the benefits which have accrued to mankind through an
understanding of the laws of electricity.
</p>

<p>
Of course, mind creates negative conditions just as readily as favorable
conditions, and when we consciously or unconsciously visualize every kind of
lack, limitation and discord, we create these conditions; this is what many are
unconsciously doing all the time.
</p>

<p>
This law as well as every other law is no respecter of persons, but is in
constant operation and is relentlessly bringing to each individual exactly what
he has created; in other words, "Whatsoever a man soweth that shall he also
reap."
</p>

<p>
Abundance, therefore, depends upon a recognition of the laws of Abundance, and
the fact that Mind is not only the creator, but the only creator of all there
is. Certainly nothing can be created, before we know that it can be created and
then make the proper effort. There is no more Electricity in the world today
than there was fifty years ago, but until someone recognized the law by which it
could be made of service, we received no benefit; now that the law is
understood, practically the whole world is lit by it. so with the law of
Abundance; it is only those who recognize the law and place themselves in
harmony with it, who share in its benefits.
</p>

<p>
The scientific spirit now dominates every field of effort, relations of cause
and effect are no longer ignored.
</p>

<p>
The discovery of a region of law marked and epoch in human progress. It
eliminated the element of uncertainty and caprice mens lives, and substituted
law, reason and certitude.
</p>

<p>
Men now understand that for every result there is an adequate and definite
cause, so that when a given result is desired, they seek the condition by which
alone this result may be attained. 
</p>

<p>
The basis upon which all law rests was discovered by inductive reasoning which
consists of comparing a number of separate instances with one another until the
common factor which gives rise to them all is seen.
</p>

<p>
It is this method of study to which the civilized nations owe the greater part
of their prosperity and the more valuable part of their knowledge; it has
lengthened life, it has mitigated pain, it has spanned rivers, it has brightened
the night with the splendor of day, extended the range of vision, accelerated
motion, annihilated distance, facilitated intercourse, and enabled men to
descend into the sea, and into the air, what wonder then that men soon
endeavored to extend the blessings of this system of study to their method of
thinking, so that when it became plainly evident that certain results followed a
particular method of thinking it only remained to classify these results.
</p>

<p>
This is method is scientific, and it is the only method by which we shall be
permitted retain that degree of liberty and freedom which we have been
accustomed to look upon as an inalienable right, because a people is safe at
home and in the world only if national preparedness mean such things as growing
surplus of health, accumulated efficiency in public and private business of
whatever sort, continuous advance in the science and art of acting together, and
the increasingly dominant endeavor to make all of these and all other aspects of
national development center and revolve about ascending life, single and
collective, for which science, art and ethics furnish guidance and controlling
motives.
</p>

<p>
The Master Key is based on absolute scientific truth and will unfold the
possibilities that lie dormant in the individual, and teach how they may be
brought into powerful action, to increase the person's effective capacity,
bringing added energy, discernment, vigor and mental elasticity. The student who
gains an understanding of the mental laws which re unfolded will come into the
possession of an ability to secure results hitherto undreamed of, and which has
rewards hardly to be expressed in words.
</p>

<p>
It explains the correct use of both the receptive and active elements of the
mental nature, and instructs the student in the recognition of opportunity; it
strengthens the will and reasoning powers, and teaches the cultivation and best
uses of imagination, desire, the emotions and the intuitional faculty. It gives
initiative, tenacity of purpose, wisdom of choice, intelligent sympathy and a
thorough enjoyment of life on its higher planes.
</p>

<p>
The Master Key teaches the use of Mind Power, true Mind Power, not any of the
substitutes and perversions; it has nothing to do with Hypnotism, Magic or any
of the more or less fascinating deceptions by which many are led to think that
something can be had for nothing.
</p>

<p>
The Master Key cultivates and develops the understanding which will enable you
to control the body and thereby the health. It improves and strengthens the
Memory. It develops Insight, the kind of Insight which is so rare, the kind
which is the distinguishing characteristic of every successful business man, the
kind which enables men to see the possibilities as well as the difficulties in
every situation, the kind which enables men to discern opportunity close at
hand, for thousands fail to see opportunities almost within their grasp while
they are industriously working with situations which under no possibility can be
made to realize any substantial return.
</p>

<p>
The Master Key develops Mental Power which means that others instinctively
recognize that you are a person of force, of character - that they want to do
what you want them to do; it means that you attract men and things to you; that
you are what some people call "lucky", that "things" come you way' that you have
come into an understanding of the fundamental laws of Nature, and have put
yourself in harmony with them; that you are in tune with Infinite; that you
understand the law of attraction, the Natural laws of growth, and the
Psychological laws on which all advantages in the he social and business world
rest.
</p>

<p>
Mental Power is creative power, it gives you the ability to create for yourself;
it does not mean the ability to take something away from some one else. Nature
never does things that way. Nature makes two blades for grass grow where one
grew before, and Mind Power enables men to do the same thing.
</p>

<p>
The Master Key develops insight and sagacity increased independence, the ability
and disposition to be helpful' it destroys distrust, depression, fear,
melancholia, and every form of lack limitation and weakness, including pain and
disease; it awakens buried talents, supplies initiative, force, energy, vitality
- it awakens an appreciation of the beautiful in Art, Literature and Science.
</p>

<p>
It has changed the lives of thousands of men and women, by substituting definite
principles for uncertain and hazy methods - and principles for the foundation
upon which every system of efficiency must rest.
</p>

<p>
Elbert Gary, the chairman of the United States Steel Corporation, said "The
services of advisors, instructors, efficiency experts in successful management
are indispensable to most business enterprises of magnitude, but I deem the
recognition and adoption of right principles vastly more importance. "The Master
Key teaches right principles, and suggests methods for making a practical
application of the principles; in that it differs from every other course of
study. It teaches that the only possible value which can attach to any principle
is in its application. Many read books, take home study courses, attend lectures
all their lives without ever making any progress in demonstrating the value of
the principles involved. The Master Key suggests methods by which the value of
the principles taught may be demonstrated and put in actual practice in the
daily experience.
</p>

<p>
There is a change in the thought of the world. This change is silently
transpiring in our midst, and is more important than any which the world has
undergone since the downfall of Paganism.
</p>

<p>
The present revolution in the opinions of all classes of men, the highest and
most cultured of men as well as those of the laboring class, stands unparalleled
in the history of the world.
</p>

<p>
Science has of late mad such vast discoveries, has revealed such an infinity of
resources, has unveiled such enormous possibilities and such unsuspected forces,
that scientific men more and more hesitate to affirm certain theories as
established and indubitable or to deny certain other theories as absurd or
impossible, and so a new civilization is being born' customs, creeds, and
cruelty are passing; vision, faith and service are taking their place. The
fetters of tradition are being melted off from humanity, and as the dross of
materialism is being consumed, thought is being liberated and truth is rising
full orbed before an astonished multitude.
</p>

<p>
The whole world is on the eve of a new consciousness, a new power and a new
consciousness, a new power and a new realization of the resources within the
self. The last century saw the most magnificent material progress in history.
The present century will produce the greatest progress in mental and spiritual
power.
</p>

<p>
Physical Science has resolved matter into molecules, molecules into atoms, atoms
into energy, and it has remained for Sir Ambrose Fleming, in an address before
the Royal Institution, to resolve this energy into mind. He says: "In its
ultimate essence, energy may be incomprehensible by us except as an exhibition
of the direct operation of that which we call Mind or Will."
</p>

<p>
Let us see what are the most powerful forces in Nature. In the mineral world
everything is solid and fixed. In the animal and vegetable kingdom it is in a
state of flux, forever changing, always being created and recreated. In the
atmosphere we find heat, light and energy. Each realm becomes finer and more
spiritual as we pass from the visible to the invisible, from the coarse to the
fine, from the low potentiality to high potentiality. When we reach the
invisible we find energy in its purest and most volatile state.
</p>

<p>
And as the most powerful forces of Nature are the invisible forces, so we find
that the most powerful forces of man are his invisible forces, his spiritual
force, and the only way in which the spiritual force can manifest is through the
process of thinking. Thinking is the only activity which the spirit possesses,
and thought is the only product of thinking.
</p>

<p>
Addition and subtraction are therefore spiritual transactions; reasoning is a
spiritual process; ideas are spiritual conceptions; questions are spiritual
searchlights and logic, argument and philosophy is spiritual machinery.
</p>

<p>
Every thought brings into action certain physical tissue, parts of the brain,
nerve or muscle. This produces an actual physical change in the construction of
the tissue. therefore it is only necessary to have a certain number of thoughts
on a given subject in order to bring about a complete change in the physical
organization of a man.
</p>

<p>
This is the process by which failure is changed to success. Thoughts of courage,
power, inspiration, harmony, are substituted for thoughts of failure, despair,
lack, limitation and discord, and as these thoughts take root, the physical
tissue is changed and the individual sees life in a new light, old things have
actually passed away, all things have become new, he is born again, this time
born of the spirit, life has a new meaning for him, he is reconstructed and is
filled with joy, confidence, hope, energy. He sees opportunities for success to
which he was heretofore blind. He recognizes possibilities which before had no
meaning for him. The thoughts of success with which he has been impregnated are
radiated to those around him, and they in turn help him onward and upward; he
attract to him new and successful associates, and this in turn changes his
environment; so that by this simple exercise of thought, a man changes not only
himself, but his environment, circumstances and conditions.
</p>

<p>
You will see, you must see, that we are at the dawn of a new day; that the
possibilities are so wonderful, so fascinating, so limitless as to be almost
bewildering. A century ago any man with and aeroplane or even a Gatling gun
could have annihilated a whole army equipped with the implements of warfare then
in use. So it is at present. Any man with a knowledge of the possibilities
contained in the Master Key has an inconceivable advantage over the multitude. 
</p>


