<h3>The Master Key System</h3>

<p>
The Master Key System, written by Chales F. Haanel, who is regarded 
by many as the father of personal development is still unknown to the large public. 
While he was, and is, 
an influential person, writer, and business man, he is still not 
recognized by many. The Master Key System is one of the first books 
he has written, and has risen in popularity since it was quoted in 
the personal development movie The Secret. This book, originally developed as a 
correspondence course, is considered by many one of the fundamental 
books on personal development. 
</p>

<p style="float: right;padding-left: 10px;">
<object width="320" height="265"><param name="movie" value="http://www.youtube.com/v/wA75avC4J5I&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/wA75avC4J5I&hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="320" height="265"></embed></object>
</p>

<p>
This online mailcourse is completely free of charge. For a preview of the content read the <a href="/forward">Forward</a>, or <strong>play the video</strong> on the right by clicking on the play icon.
</p>
          
<p>
This domain reintroduces the original mailcourse as written by Charles F. Haanel. After registration 
you will be granted access to the member area and the first chapter will be unlocked. Every week another 
chapter will be unlocked. As intended by the original author. The information is exact and concise, only 
the essential information is communicated and if followed will change the readers mentality. This book is 
a gift to mankind.
</p>

