<h3>Terms</h3>

<p>
Below described the Terms of Use of the Master Key System. Master Key System is
an Innovita product.
</p>

<p>
A member or registrant of the Master Key System applications, is a subscriber
to the application. On the moment of subscribing, that is submitting the
registration form. This member agrees with the following terms.
</p>

<p>
The publisher, is the company behind this domain.
</p>

<h4>1. Service &amp; Liability</h4>
<p>
The Master Keys system is an application that serves content. A registrant will
be able to read the complete content in 24 weeks. The makers take no
responsibility for applying this knowledge or any harm directly of indirectly
following from the application of this knowledge.
</p>

<h4>2. Privacy</h4>
<p>
Member will supply personal details to the application. Consisting of at least an
email-address. Innovita is free to use the supplied information to notify the
registrant of new or related activities. These activities can be initiated by
the publisher or any partner of the publisher.
</p>

<h4>3. Publisher</h4>
<p>
Publisher is free to decide to discontinue the service. Or make any adaptations
publisher sees fit.
</p>
